os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install --upgrade pyyaml requests websockets
script:
  - pip freeze
  - python setup.py test
