# Minimal yamllint config - essential rules only
extends: default

rules:
  # Match ruff line length
  line-length:
    max: 120
    level: warning
  
  # Flexible document structure
  document-start: disable
  
  # Essential formatting
  indentation:
    spaces: 2
  quoted-strings:
    required: only-when-needed
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
